### ISSUE TITLE
Stuck on CONCATINATING 100%

### ISSUE THREAD

**Issue by jaaaamIron** [benhackbarth/audioguide#4]
Hi. I'm trying to run agConcatenate on a c. 30" soundfile, and am running into an issue where CONCATINATING gets stuck at 100%, and the process never actually completes - it's going on 5 hours now that I've let it run, and I've tried a few times for a shorter amount of time previously.
Below 100% it says:
rching @ 0.95 x 44   search pass lengths: 1194  298  1
rching @ 16.32 x 42  search pass lengths: 1195  298  1 
(and it rapidly switches between these error messages, in a loop in which the first two values change (but repeat))

I have previously run audioguide fine a few months ago, so it may be an issue with my setup, but I'm not sure what it could be (no error messages etc). Do you have any idea what it may be/suggestions for me to diagnose it?

**Comment by benhackbarth** [comment]
Hello,

I've seen errors like this from time to time. It is usually due to having a corpus of sounds that start in silence. I'm essence, the selection process never finishes because nothing tells audioguide to stop since the subtractive amplitude model no like lnger functions properly. See here for more details https://www.youtube.com/watch?v=V3MgfbaDi9I&t=1406s

There are two ways to fix this. First: add a hard threshold for the maximum number of corpus sounds that may be picked per target segment. This is done with si(maxSegment=5) for a limit of 5. Second is to try using agSegment.py to segment all of your corpus files, including any of those which are single segments per file. You can use wildcards for this python3 agSegment.py myfolder/*.wav. This will remove any silences at the start of segments.

If neither of these fix your issue, please attach your options file and the resulting log.html please.
