### ISSUE TITLE
acoustic scrore error

### ISSUE THREAD

**Issue by zseramnay** [benhackbarth/audioguide#5]
Hello Ben
Meilleurs voeux  à toi !

I'm having issues working with simple acoustic scores with 1.74...

The error is :

(base) yan-MBP-Retina:audioguide-1.74 yanmaresz$ python agConcatenate.py /Users/yanmaresz/kDrive/Apps/audioguide-yan/_Yan-Audioguide/AG-ymScripts/AG-creatingAnAcousticScore.py 
audioguide1.74 -> /Users/yanmaresz/kDrive/Apps/audioguide-1.74/audioguide
python3.9.7 -> /Users/yanmaresz/opt/anaconda3/bin/python
                 Evaluating TARGET coq.wav from 0.00-2.20                 
100% [================================================================]
	Found 5 segments (threshold=-36.0 offsetrise=1.50 offsetthreshadd=12.00). 

                           Evaluating CORPUS...                           
100% [================================================================]
	Read 41/59 segments (69%, 4.36 min.)                                      

LIMITS
power-seg > 30%
	removed 18 (30.5%) segments from ord

                              CONCATINATING                               
100% [================================================================]
	Selected 0 events                                                         

Traceback (most recent call last):
  File "/Users/yanmaresz/kDrive/Apps/audioguide-1.74/agConcatenate.py", line 29, in <module>
    ag.execute()
  File "/Users/yanmaresz/kDrive/Apps/audioguide-1.74/audioguide/__init__.py", line 68, in execute
    files = self.write_concatenate_output_files()
  File "/Users/yanmaresz/kDrive/Apps/audioguide-1.74/audioguide/__init__.py", line 439, in write_concatenate_output_files
    output['outputparse'] = {'simultaneousSelections': int(max([d['simultaneousSelectionNumber'] for d in output['selectedEvents']])+1), 'classifications': max(self.ops.OUTPUTEVENT_CLASSIFY['numberClasses'], 1), 'corpusIds': int(max([d['corpusIdNumber'] for d in output['selectedEvents']])+1)}
ValueError: max() arg is an empty sequence

**Comment by benhackbarth** [comment]
Hello Yan,

happy new year.

there is a small bug here, but the real issue is that AG isn't selecting any events ("Selected 0 events"). Could you please attach your options file as well as the resulting log.html?

Best, Ben

**Comment by zseramnay** [comment]
Thanks Ben,

The file is super simple.. im' preparing a class for monday.
No log. AG creates bachroll, targetlabels then stops.
[AG-creatingAnAcousticScore.txt](https://github.com/benhackbarth/audioguide/files/7875324/AG-creatingAnAcousticScore.txt)

**Comment by benhackbarth** [comment]
Thanks Yan.

Could you send me the target and corpus files over wetransfer?

**Comment by zseramnay** [comment]
Here you go.
https://www.swisstransfer.com/d/39373608-a54f-4cd4-98a8-731274b171c8

Thanks Ben
Yan

**Comment by benhackbarth** [comment]
Thanks. 
This isn't a bug. What is happening is that all of the piano sounds are louder than any of the rooster segments. So, none of the corpus sounds get past the first spass() object, which tells audioguide to discard any sounds that are louder than each target segment (in this case, the entire corpus gets tossed). I made it so that this issue is easier to see in log.html and I added an error message pointing you to log.html in case the program fails like this. This is all now in git. Could you let me know if this works on your original options file?

Regarding the example, know that, because you're using corpus sounds without pitches written into the filenames, AG will use centroid to estimate fundamental frequency. So pitches might not look right in the bachroll. You can try adjusting the csf(midiPitchMethod) to something like csf(midiPitchMethod) to 'f0-seg'. See [here](http://www.benhackbarth.com/audioGuide/docs_v1.74.html#midiPitchMethod). Or use a piano database with pitches in the filenames.

Here is my take on your options file. Loose the first spass, the add scaleDb=-12 to the csf() to make it softer. I also tweaked the tsf() segmentation somewhat. Finally, I added made a 2-stave piano part with polyphonic possibilities.
[AG-creatingAnAcousticScore.txt](https://github.com/benhackbarth/audioguide/files/7876666/AG-creatingAnAcousticScore.txt)

**Comment by zseramnay** [comment]
Ahh, I see...
My bad.
And many thanks for the tips !

Best
Yan

**Comment by benhackbarth** [comment]
No problem Yan
